### ISSUE TITLE
deployment, how does it work!?

### ISSUE THREAD

**Issue by igalic** [puppet-community/puppetcommunity-extlib#10]
thanks to @nibalizer's https://github.com/puppet-community/puppetcommunity-extlib/pull/5 we've setup auto-deployment.

we've now reduced the amount of noise #6 & #8, and, set our currect forge name #7 (we've got the /puppet namespace. isn't that cool ;)

i've pushed out new tags: ([v0.9.3](https://github.com/puppet-community/puppetcommunity-extlib/releases/tag/v0.9.3)), and travis "built" and deployed it [to the forge](https://forge.puppetlabs.com/puppet/extlib).

the problem is, that it [built](https://travis-ci.org/puppet-community/puppetcommunity-extlib/builds/54677900) and attempted to deploy this thing seven times:

https://travis-ci.org/puppet-community/puppetcommunity-extlib/jobs/54677916
https://travis-ci.org/puppet-community/puppetcommunity-extlib/jobs/54677915
https://travis-ci.org/puppet-community/puppetcommunity-extlib/jobs/54677914
https://travis-ci.org/puppet-community/puppetcommunity-extlib/jobs/54677913
https://travis-ci.org/puppet-community/puppetcommunity-extlib/jobs/54677912
https://travis-ci.org/puppet-community/puppetcommunity-extlib/jobs/54677911
https://travis-ci.org/puppet-community/puppetcommunity-extlib/jobs/54677910
https://travis-ci.org/puppet-community/puppetcommunity-extlib/jobs/54677909

and, i have no idea what a successful attempt looks like.

**Comment by igalic** [comment]
@carlossg & @raphink: halp plz ._.

**Comment by carlossg** [comment]
Puppet is looking for `Modulefile`, seems that it only checks for `metadata.json` in 3.6+

Probably Travis should avoid packaging the module unless it is going to deploy it

**Comment by nibalizer** [comment]
Also camptocamp sets puppet version with ruby version so that when the rvm is contained only one puppet verison is set, I think. https://github.com/camptocamp/puppet-puppetserver/blob/master/.travis.yml#L7 It may be iterating down the puppet version env vars.

**Comment by carlossg** [comment]
Just try adding something like

    condition: "$PUPPET_VERSION = '~> 3.6.0'"

to .travis.yml

**Comment by igalic** [comment]
i'm actually considering to further reduce the matrix, just like @camptocamp have…

**Comment by carlossg** [comment]
IMO it's not necessary to test multiple ruby versions, just puppet versions

**Comment by igalic** [comment]
i wish i could agree :( but our travis failing on 1.8.7 kinda shows it is necessary, because subtle changes in libraries can make a huge difference.

and then there's that whole Hash sorting order in 1.8 vs 1.9, throwing your idempotence out the window if you forgot to add a `.sort`

**Comment by igalic** [comment]
following #11, and 7fba86e979815c180f3f5b813d2e2bb394f84ecb, we can close this.
